# Generated by Django 5.0.7 on 2026-10-06 17:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='ticker')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('sector', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('financials', 'Financials'), ('consumer_discretionary', 'Consumer Discretionary'), ('consumer_staples', 'Consumer Staples'), ('industrials', 'Industrials'), ('energy', 'Energy'), ('materials', 'Materials'), ('utilities', 'Utilities'), ('real_estate', 'Real Estate'), ('communication_services', 'Communication Services')], db_index=True, max_length=50, verbose_name='sector')),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='market cap')),
                ('per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PER')),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ROE')),
                ('working_capital', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='working capital')),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='total assets')),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='retained earnings')),
                ('ebit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='EBIT')),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='total liabilities')),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='sales')),
                ('equity_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='equity value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['-market_cap'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='phone number')),
                ('user_type', models.CharField(choices=[('retail', 'Retail Investor'), ('institutional', 'Institutional Investor')], default='retail', max_length=20, verbose_name='user type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='query')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'search history',
                'verbose_name_plural': 'search history',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
